services:
  db:
    image: postgres:15-alpine
    container_name: football_posters_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=football_posters
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
